### ISSUE TITLE
TO_TIMESTAM function does not recognize MMM - 3 char abreviation

### ISSUE THREAD

**Issue by cristiangabor** [JamesSkemp/logparserplus.com#2]
The following date 
`'24 Jun 2011 13:22:21', 'dd MMM yyyy HH:mm:ss'`
fails to return a timestamp due to MMM not being able to recognize the 3 Month abbreviation

Please fix it

**Comment by JamesSkemp** [comment]
Hi Cristian.

Unfortunately I can't replicate that.

    .\LogParser.exe "select top 1 TO_TIMESTAMP('24 Jun 2011 13:22:21', 'dd MMM yyyy HH:mm:ss') from '\path\to\u_ex19*.log'"

Can you provide the full query so I can try to repeat it on my end?

**Comment by JamesSkemp** [comment]
Before I close this, wanted to follow-up one more time. :)

**Comment by JamesSkemp** [comment]
Closing this out, but don't hesitate to reach out with the full query, if you still can't get it to work.
